### PR TITLE
fix index type for SparseArrays

### LINKED ISSUE #46: visualization of SparseArray fails with non Int indices in Julia 1.7
In Julia 1.6, length always returns an Int
```
julia> using SparseArrays
julia> typeof(length(sparsevec(Dict(Int32(1)=>2), 1)))
Int64
```

In Julia 1.7, length returns the type of the indices eltype.
```
julia> using SparseArrays
julia> typeof(length(sparsevec(Dict(Int32(1)=>2), 1)))
Int32
```

So when expanding a Sparse vector in the VARIABLES panel of "Run and Debug", I get the followin error:

```
Error while running the debugger (consider adding a breakpoint for uncaught exceptions):
ERROR: TypeError: in keyword argument indexedVariables, expected Union{Missing, Int64}, got a value of type Int32
Stacktrace:
 [1] construct_return_msg_for_var(state::VSCodeServer.DebugAdapter.DebuggerState, name::String, value::SparseArrays.SparseVector{Float32, Int32})
   @ VSCodeServer.DebugAdapter ~/.vscode-server/extensions/julialang.language-julia-1.4.3/scripts/packages/DebugAdapter/src/debugger_requests.jl:573
 [2] variables_request(conn::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, state::VSCodeServer.DebugAdapter.DebuggerState, params::VSCodeServer.DebugAdapter.VariablesArguments)
   @ VSCodeServer.DebugAdapter ~/.vscode-server/extensions/julialang.language-julia-1.4.3/scripts/packages/DebugAdapter/src/debugger_requests.jl:717
 [3] (::VSCodeServer.DebugAdapter.var"#128#154"{VSCodeServer.DebugAdapter.DebuggerState})(conn::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::VSCodeServer.DebugAdapter.VariablesArguments)
   @ VSCodeServer.DebugAdapter ~/.vscode-server/extensions/julialang.language-julia-1.4.3/scripts/packages/DebugAdapter/src/packagedef.jl:58
 [4] dispatch_msg(x::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::VSCodeServer.JSONRPC.MsgDispatcher, msg::Dict{String, Any})
   @ VSCodeServer.JSONRPC ~/.vscode-server/extensions/julialang.language-julia-1.4.3/scripts/packages/JSONRPC/src/typed.jl:67
 [5] macro expansion
   @ ~/.vscode-server/extensions/julialang.language-julia-1.4.3/scripts/packages/DebugAdapter/src/packagedef.jl:76 [inlined]
 [6] (::VSCodeServer.DebugAdapter.var"#143#169"{VSCodeServer.var"#88#90", VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, VSCodeServer.JSONRPC.MsgDispatcher})()
   @ VSCodeServer.DebugAdapter ./task.jl:411
```

### PR DESCRIPTION
**Pull request by dpinol**
Fixes #46.

### CODE REVIEW

**Comment by pfitzseb** [comment]
This is gonna fail for arrays with more than `typemax(Int32)` arguments on x86 machines, right? Probably makes sense to move to `Int64` for the `Variable` struct definition instead.

**Comment by dpinol** [comment]
> 
> 
> This is gonna fail for arrays with more than `typemax(Int32)` arguments on x86 machines, right? Probably makes sense to move to `Int64` for the `Variable` struct definition instead.

good point, I changed all indexedVariables types to Union{Missing,Int64}

**Comment by dpinol** [comment]
@pfitzseb hi, how do you see this PR? what's missing to be able to merge it? thanks

**Comment by pfitzseb** [comment]
Nothing missing, I just forgot about it...

**Review by pfitzseb — APPROVED** [review]

**Pull request merged**
