### PR TITLE
Added marshaling for JSON <-> Dict <-> ProtocolMessages, and stubs for handlers.

### PR DESCRIPTION
**Pull request by twadleigh**
- Added marshaling from `Dict` for all the types, including for a generic `ProtocolMessage`.
- Added project environment boilerplate.
- Merged in server handling stubs.

### CODE REVIEW

**Comment by ZacLN** [comment]
Looking good. Do you think we could avoid the name obfuscating macros? I feel like it could be confusing for other wanting to use/contribute to this

**Comment by twadleigh** [comment]
I'm now much happier with the serialization story and the type definitions in general.
The serialization to JSON does depend on https://github.com/JuliaIO/JSON.jl/pull/288 getting merged.

**Comment by twadleigh** [comment]
I cherrypicked over your addition of handler stubs and refactored them according to the revised definition of the structs. What's there currently loads without error.

The skeleton is looking like it is nearing completion. I think it is time to merge this PR, which has already grown well beyond its initial scope.

**Comment by twadleigh** [comment]
And, BTW, @ZacLN, thanks for all your help on this. I'm looking forward to a fruitful collaboration.

**Comment by davidanthoff** [comment]
@twadleigh I'm going to close this because the debugger story in VS Code has moved on in the meantime. I am currently moving all the debugger code out of the extension into this package, but it is quite a different design. We are now using JSONRPC as the transport channel, for example.

**Pull request closed without merging**
