### PR TITLE
better printing for "step into targets"

### LINKED ISSUE #14: Nicer presentation of step in targets
Sometimes it displays things like `QuoteNode` in the label of the step in targets, there is probably some cleanup we could do there.

In particular, looking at the example in our announcement:
- I think instead of `sin(4)` and `cos(9)`, it should probably show `sin(x)` and `cos(y)`.
- The third entry would ideally show as `thisisglobal + sin(x) + cos(y)`. If we can't recover the inplace notation, I think even `+(thisisglobal, sin(x), cos(y))` would be nicer.

### PR DESCRIPTION
**Pull request by pfitzseb**
image

It might make sense to show this *with* the SSA targets (e.g. `%3 = cos(x)` etc) so it's more obvious what's being evaluated. Thoughts?

Fixes #14.

### CODE REVIEW

**Comment by aviatesk** [comment]
> It might make sense to show this with the SSA targets (e.g. %3 = cos(x) etc)

SSA there would basically end up showing something like ordered-list numbers (those not necessarily starting with 1.) in the left of those "step into target"s list, right ? If I so'm not sure how it can be useful tbh.

Well, if VSCode starts to support some UI like Juno's "Current code" view, I guess showing a bit of internals of JuliaInterpreter there would be somewhat useful (like we does so when debugging code in untitled editor in Juno).

**Comment by pfitzseb** [comment]
It's useful because right now you can't really know what `%4` refers to, but if we also who `%2 = cos(x)`, `%3 = tan(y)`, and `%4 = +(%2, %3)` then you can at least figure it out. I thought about recursively interpolating the defining expressions, but that'd get too verbose.

**Comment by aviatesk** [comment]
aha, makes sense. I agree with the idea (showing SSA numbers) then.

**Comment by pfitzseb** [comment]
Looks like this now:
image

**Comment by aviatesk** [comment]
looks nice, imho.

**Comment by davidanthoff** [comment]
What about
```
cos(x)
tan(y)
+(cos(x), tan(y))
atan(z)
-(cos(x) + tan(y),  atan(z))
sin(cos(x) + tan(y) - atan(z))
```

**Comment by pfitzseb** [comment]
That's fine in simple cases like this, but is a mess as soon as your expressions are slightly longer.

**Comment by davidanthoff** [comment]
Could the longer strings just be trimmed, like:
```
sin(cos(x) + ...
```
That might still be easier to link back to the actual source code than introducing slot names? Not sure...

We don't have tooltips for the menu items, right?

**Comment by pfitzseb** [comment]
Bump.

**Review by aviatesk — APPROVED** [review]
imho this could be merged as is and we can iterate on it later if needed.

**Pull request merged**
